### ISSUE TITLE
Throws error on double embedded comments

### ISSUE THREAD

**Issue by sims120** [dsp444/save_canvas_discussion#4]
Thanks for making this script available. Super helpful.

However, I found that the script sometimes throws an error (that kills the script, leaving some comments unextracted). Inspection of the original json file suggests that the script dies when the json output from a canvas discussion board has a double-embedded comment (i.e. a response to a response to a comment). Error message:

Traceback (most recent call last):
  File "save_canvas_discussion.py", line 234, in <module>
    get_discussion_posts( sys.argv[1] )
  File "save_canvas_discussion.py", line 183, in get_discussion_posts
    write_post_to_file( os.path.dirname( fname ), name, id, post['message'], post['updated_at'], id_to_name, os.path.basename( fname ).split('.')[0], replies )
  File "save_canvas_discussion.py", line 97, in write_post_to_file
    write_replies_to_file( fname, id, replies, id_to_name, WIDTH )
  File "save_canvas_discussion.py", line 129, in write_replies_to_file
    write_replies_to_file( path, name, id, reply['replies'], id_to_name, width )
NameError: global name 'path' is not defined

**Comment by dsp444** [comment]
Thank you for pointing this out - I failed to test it with responses to responses and therefore missed this line.  It is fixed now in the master branch.
